### ISSUE TITLE
Use `'@container': '@language'` in the `@context` to define the structure of the generated `classes`

### ISSUE THREAD

**Issue by KristofVDB1** [Informatievlaanderen/OSLO-UML-Transformer#67]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

We're using the `@oslo-flanders/ea-converter` package to generate an RDF-file which works well. However, we have some questions in regards to the flexibility of the generated output. 

A lot of the key/values have the same structure. For example, if we look at `apLabel`, this is the structure: 
```json
"apLabel": [
    {
        "@language": "nl",
        "@value": "Oplegger"
    }
]
```
The output itself is correct, however it deviates a bit from the existing output that got generated from the previous toolchain version. The old output was this:
```json
"ap-label-nl": {
    "nl": "Oplegger"
},

```

The fact that the name from the key changed from `ap-label-nl` to `apLabel` is no problem, however we are looking to replicate the behaviour from the old toolchain where the nested key of the label-object is the language for which the label got generated with the value of the label. In order to achieve this, we tried to change the predefined `@context` that is passed to the generated RDF from [here](https://github.com/Informatievlaanderen/OSLO-UML-Transformer/blob/main/packages/oslo-converter-uml-ea/lib/utils/osloContext.ts) to something like this:

````ts

    apLabel: {
      '@id': 'oslo:apLabel',
      '@container': '@language',
    }
````
We replaced the previous `@container` value from `@set` to `@language` but that does not seem to have any impact on the generated output. 

I looked a bit deeper into the code and found out that the generated output seems to be constructed manually using [this method](https://github.com/Informatievlaanderen/OSLO-UML-Transformer/blob/main/packages/oslo-converter-uml-ea/lib/output-handlers/JsonLdOutputHandler.ts#L312). This lead me to believe that the passed `@context` file doesn't have any impact on the generated output (at least for this specific use-case). 

My question is: 
Is there a way that we can make the generated output `@context`-dependant to generate the `apLabel` in the same format as the previous `ap-label-nl` or is that not possible without reworking the `mapToLiteral` method as mentioned earlier? We hoped that it would be possible to change the generated output using the `@context` but that might be a wrong expectation from our side.

Thanks in advance for any insights!

**Comment by KristofVDB1** [comment]
@ddvlanck I would love to have your insights on this issue. Feel free to answer whenever you deem it possible. Thanks for any help!

**Comment by ddvlanck** [comment]
Hi Kristof,

First some background information. There is a reason why we did not use a JSON-LD serializer package as there are multiple packages available on NPM and it is simple: debugging purposes. We construct our own OSLO-specific JSON-LD output, with keys as `classes`, `properties`, ... so that developers, but also editors can easily verify the output and spot mistakes if there are any. This OSLO-specific format can not be created when you use one of the available packages. 

By using of our own OSLO-specific JSON-LD format, we have to create our own JSON-LD context, but also our own objects. You're correct that only changing the `@container` value from `@set` to `@language` in the context will not provide the correct output. So if you want to accomplish the same behavior as in the previous toolchain, you will have to update the JSON-LD context as shown in your example, but also update the `mapLiteral` function.

**Comment by KristofVDB1** [comment]
@ddvlanck Thanks for the answer! That was indeed what I expected the outcome to be based on the code. Just wanted to see if there was something that I might have overlooked? Thank you for taking the time to answer this one! Will close this as it's resolved in a way 👍
