### ISSUE TITLE
correct the documentation for the SHACL generator

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-UML-Transformer#76]
The SHACL generator CLI has different parameters than the one documented in the README. 
Lets align the documentation with the implementation.

**Comment by KristofVDB1** [comment]
@bertvannuffelen I tried running all the different API options and they all seem to generate a shacl output. I did however change the `--language` flag to `nl` in the `README` since this will be the preferred choice over `en` (https://github.com/Informatievlaanderen/OSLO-UML-Transformer/commit/524da6051c754824a882dd8d61d7fcb34e6c8099). Maybe that caused some confusion because this probably will not have worked for a lot of models. 

If it's something else, please be sure to add here what does not work!
